image: jamesdbloom/mockserver:build

script:
  - mvn install -q -Dmaven.test.skip=true -DskipTests -DskipITs -DskipRubyBuild=true
  - mvn install

notify:
  email:
    recipients:
      - jamesdbloom@gmail.com
